[options]
input = './slhaFiles/SlepSlep_400_200_SLHA.dat'
checkmateFolder = './CheckMATE'
ncpu = 5
cleanUp = False

[CheckMateParameters]
Analyses = atlas_1908_08215
InvisiblePIDs = 1000022
QuietMode = True
OutputExists = 'overwrite'
OutputDirectory =  './run_02_SlepSlep'
TotalResultFileColumns: analysis,sr,robs,rexp,s,ds,eff,signalsumofweights,s95obs,robscons,rexpcons
WritePythiaEvents = True
WriteDelphesEvents = True
MultiBin = detailed
CLs = True
Uplim = True
Model = full
Statonly = False
#Backend = jax

[CheckMateProcess]
Name = "SlepSlep"
MGcommand = "import model MSSM_SLHA2\n define sl+ = el+ er+ mul+ mur+\n define sl- = el- er- mul- mur-\n generate p p > sl+ sl-;"
MaxEvents = 25000
MGparam = ${CheckMateParameters:SLHAfile}

