[options]
input = './slhaFiles/HeHe*.dat'
checkmateFolder = './CheckMATE'
ncpu = 5
cleanUp = True

[CheckMateParameters]
Analyses = atlas_1908_08215
InvisiblePIDs = 255
QuietMode = True
OutputExists = 'overwrite'
OutputDirectory =  './HeHe_ee'
TotalResultFileColumns: analysis,sr,robs,rexp,s,ds,eff,signalsumofweights,s95obs,robscons,rexpcons
WritePythiaEvents = False
WriteDelphesEvents = False
#MultiBin = detailed
#CLs = True
#Uplim = True
#Model = fullpyhf
#Statonly = False

[CheckMateProcess]
Name = "HeHe_ee"
MGcommand = "import model ../../models/LesHouchesModelFreezeIn-leptons_UFO\n generate p p > ~HE ~he, (~he > e- ~s0), (~HE > e+ ~s0);"
MaxEvents = 25000
MGparam = ${CheckMateParameters:SLHAfile}

