(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"LesHouchesModelFreezeIn-leptons",
  Authors -> {"Genevieve Belanger, Nishita Desai, Andreas Goudelis, Julia Harz, Andre Lessa, Jose Miguel No, Alexander Pukhov, Sezen Sekmen, Dipan Sengupta, Bryan Zaldivar, Jose Zurita"},
  Version -> "1.0",
  Date -> "03.11.2018"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], h -> S[1], G0 -> S[2], GP -> S[3], s0 -> S[4], HE -> F[13]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    QuantumNumbers -> {},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    QuantumNumbers -> {},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> ms0,
    Indices -> {},
    PropagatorLabel -> "s0" },

F[13] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mHE,
    Indices -> {},
    PropagatorLabel -> "HE" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ F[13] ] = GaugeXi[F[16]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
mh[ ___ ] := mh;
ms0[ ___ ] := ms0;
mHE[ ___ ] := mHE;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(2*I)*lams0h, 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(2*I)*lams0h, 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(2*I)*lams0h, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(6*I)*lams0, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[1] , S[4] , S[4] ] == {{(2*I)*lams0h*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{I*EL, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc17, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc18, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc20, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc23, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc24, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc26, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc28, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc31, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc32, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc34, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc36, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc38, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc40*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc42*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*gc42*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc42*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{gc43L*IndexDelta[e1x2, e2x2], 0}, {gc43R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{gc44L*IndexDelta[e1x2, e2x2], 0}, {gc44R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc45L*IndexDelta[e1x2, e2x2], 0}, {gc45R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc46L*IndexDelta[e1x2, e2x2], 0}, {gc46R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc47L*IndexDelta[e1x2, e2x2], 0}, {gc47R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc48L*IndexDelta[e1x2, e2x2], 0}, {gc48R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc49*IndexDelta[e1x2, e2x2], 0}, {I*gc49*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc50*IndexDelta[e1x2, e2x2], 0}, {I*gc50*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc51*IndexDelta[e1x2, e2x2], 0}, {I*gc51*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc52, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc53, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc54, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc55L, 0}, {gc55R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc56L, 0}, {gc56R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc57L, 0}, {gc57R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc58, 0}, {I*gc58, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc59, 0}, {I*gc59, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc60, 0}, {I*gc60, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{gc61L*IndexDelta[e1x2, e2x2], 0}, {gc61R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{gc62L*IndexDelta[e1x2, e2x2], 0}, {gc62R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc63L*IndexDelta[e1x2, e2x2], 0}, {gc63R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc64L*IndexDelta[e1x2, e2x2], 0}, {gc64R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc65L*IndexDelta[e1x2, e2x2], 0}, {gc65R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc66L*IndexDelta[e1x2, e2x2], 0}, {gc66R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc67*IndexDelta[e1x2, e2x2], 0}, {I*gc67*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc68*IndexDelta[e1x2, e2x2], 0}, {I*gc68*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc69*IndexDelta[e1x2, e2x2], 0}, {I*gc69*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[13] , S[4] ] == {{I*gc70, 0}, {0, 0}},

C[ -F[5] , F[13] , S[4] ] == {{I*gc71, 0}, {0, 0}},

C[ -F[6] , F[13] , S[4] ] == {{I*gc72, 0}, {0, 0}},

C[ -F[13] , F[4] , S[4] ] == {{0, 0}, {I*gc73R, 0}},

C[ -F[13] , F[5] , S[4] ] == {{0, 0}, {I*gc74R, 0}},

C[ -F[13] , F[6] , S[4] ] == {{0, 0}, {I*gc75R, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*EL^2/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{((-1/2*I)*EL)/sw, 0}},

C[ -S[3] , S[1] , V[3] ] == {{EL/(2*sw), 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((I/2)*EL)/sw, 0}},

C[ S[3] , S[1] , -V[3] ] == {{EL/(2*sw), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-2*I)*gc91, 0}, {I*gc91, 0}, {I*gc91, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-2*I)*gc93, 0}, {I*gc93, 0}, {I*gc93, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {gc94R, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {gc95R, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {gc96R, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{(EL*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*EL^2/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc106, 0}, {(-I)*gc106, 0}, {(2*I)*gc106, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-2*I)*gc111, 0}, {I*gc111, 0}, {I*gc111, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc112, 0}, {I*gc112, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc113, 0}, {I*gc113, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc114, 0}, {I*gc114, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc115*IndexDelta[e1x2, e2x2], 0}, {I*gc115*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc116*IndexDelta[e1x2, e2x2], 0}, {I*gc116*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc117*IndexDelta[e1x2, e2x2], 0}, {I*gc117*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc118*IndexDelta[e1x2, e2x2], 0}, {I*gc118*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc119*IndexDelta[e1x2, e2x2], 0}, {I*gc119*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc120*IndexDelta[e1x2, e2x2], 0}, {I*gc120*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc121*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc121*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc122*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc122*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc123*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc123*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc124*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc124*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc125*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc125*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc126*SUNT[e3x2, e1x2, e2x2], 0}, {I*gc126*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc127*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc128*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc129*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc130*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc131*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc132*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc133, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc134, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc135, 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc136, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc137, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc138, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc139L*IndexDelta[e1x2, e2x2], 0}, {I*gc139R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc140L*IndexDelta[e1x2, e2x2], 0}, {I*gc140R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc141L*IndexDelta[e1x2, e2x2], 0}, {I*gc141R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc142L*IndexDelta[e1x2, e2x2], 0}, {I*gc142R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc143L*IndexDelta[e1x2, e2x2], 0}, {I*gc143R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc144L*IndexDelta[e1x2, e2x2], 0}, {I*gc144R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc145, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc146, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc147, 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc148L, 0}, {I*gc148R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc149L, 0}, {I*gc149R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc150L, 0}, {I*gc150R, 0}},

C[ -F[13] , F[13] , V[1] ] == {{I*gc151, 0}, {I*gc151, 0}},

C[ -F[13] , F[13] , V[2] ] == {{I*gc152, 0}, {I*gc152, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc17 -> -EL,
     gc18 -> EL,
     gc20 -> -EL,
     gc23 -> EL,
     gc24 -> (cw*EL)/sw,
     gc26 -> -((cw*EL)/sw),
     gc28 -> EL,
     gc31 -> -EL,
     gc32 -> -((cw*EL)/sw),
     gc34 -> (cw*EL)/sw,
     gc36 -> -((cw*EL)/sw),
     gc38 -> (cw*EL)/sw,
     gc40 -> -GS,
     gc42 -> GS^2,
     gc43L -> yb,
     gc43R -> -yt,
     gc44L -> ydo,
     gc44R -> -yup,
     gc45L -> ys,
     gc45R -> -yc,
     gc46L -> -(yb/Sqrt[2]),
     gc46R -> yb/Sqrt[2],
     gc47L -> -(ydo/Sqrt[2]),
     gc47R -> ydo/Sqrt[2],
     gc48L -> -(ys/Sqrt[2]),
     gc48R -> ys/Sqrt[2],
     gc49 -> -(yb/Sqrt[2]),
     gc50 -> -(ydo/Sqrt[2]),
     gc51 -> -(ys/Sqrt[2]),
     gc52 -> ye,
     gc53 -> ym,
     gc54 -> ytau,
     gc55L -> -(ye/Sqrt[2]),
     gc55R -> ye/Sqrt[2],
     gc56L -> -(ym/Sqrt[2]),
     gc56R -> ym/Sqrt[2],
     gc57L -> -(ytau/Sqrt[2]),
     gc57R -> ytau/Sqrt[2],
     gc58 -> -(ye/Sqrt[2]),
     gc59 -> -(ym/Sqrt[2]),
     gc60 -> -(ytau/Sqrt[2]),
     gc61L -> yc,
     gc61R -> -ys,
     gc62L -> yt,
     gc62R -> -yb,
     gc63L -> yup,
     gc63R -> -ydo,
     gc64L -> yc/Sqrt[2],
     gc64R -> -(yc/Sqrt[2]),
     gc65L -> yt/Sqrt[2],
     gc65R -> -(yt/Sqrt[2]),
     gc66L -> yup/Sqrt[2],
     gc66R -> -(yup/Sqrt[2]),
     gc67 -> -(yc/Sqrt[2]),
     gc68 -> -(yt/Sqrt[2]),
     gc69 -> -(yup/Sqrt[2]),
     gc70 -> -yHEeR,
     gc71 -> -yHEmuR,
     gc72 -> -yHEtaR,
     gc73R -> -yHEeR,
     gc74R -> -yHEmuR,
     gc75R -> -yHEtaR,
     gc91 -> EL^2,
     gc93 -> -(EL^2/sw^2),
     gc94R -> -ye,
     gc95R -> -ym,
     gc96R -> -ytau,
     gc106 -> -((cw*EL^2)/sw),
     gc111 -> (cw^2*EL^2)/sw^2,
     gc112 -> -EL,
     gc113 -> -EL,
     gc114 -> -EL,
     gc115 -> (2*EL)/3,
     gc116 -> (2*EL)/3,
     gc117 -> (2*EL)/3,
     gc118 -> -1/3*EL,
     gc119 -> -1/3*EL,
     gc120 -> -1/3*EL,
     gc121 -> GS,
     gc122 -> GS,
     gc123 -> GS,
     gc124 -> GS,
     gc125 -> GS,
     gc126 -> GS,
     gc127 -> EL/(Sqrt[2]*sw),
     gc128 -> EL/(Sqrt[2]*sw),
     gc129 -> EL/(Sqrt[2]*sw),
     gc130 -> EL/(Sqrt[2]*sw),
     gc131 -> EL/(Sqrt[2]*sw),
     gc132 -> EL/(Sqrt[2]*sw),
     gc133 -> EL/(Sqrt[2]*sw),
     gc134 -> EL/(Sqrt[2]*sw),
     gc135 -> EL/(Sqrt[2]*sw),
     gc136 -> EL/(Sqrt[2]*sw),
     gc137 -> EL/(Sqrt[2]*sw),
     gc138 -> EL/(Sqrt[2]*sw),
     gc139L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc139R -> (-2*EL*sw)/(3*cw),
     gc140L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc140R -> (-2*EL*sw)/(3*cw),
     gc141L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc141R -> (-2*EL*sw)/(3*cw),
     gc142L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc142R -> (EL*sw)/(3*cw),
     gc143L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc143R -> (EL*sw)/(3*cw),
     gc144L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc144R -> (EL*sw)/(3*cw),
     gc145 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc146 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc147 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc148L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc148R -> (EL*sw)/cw,
     gc149L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc149R -> (EL*sw)/cw,
     gc150L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc150R -> (EL*sw)/cw,
     gc151 -> -EL,
     gc152 -> (EL*sw)/cw};

